#===============================================================================$
#   __          __   _ _      _         _   _            _____           _      #
#   \ \        / /  | | |    (_)       | | | |          |  __ \         | |     #
#    \ \  /\  / /_ _| | | __  _ _ __   | |_| |__   ___  | |__) |_ _ _ __| | __  #
#     \ \/  \/ / _` | | |/ / | | '_ \  | __| '_ \ / _ \ |  ___/ _` | '__| |/ /  #
#      \  /\  / (_| | |   <  | | | | | | |_| | | |  __/ | |  | (_| | |  |   <   #
#       \/  \/ \__,_|_|_|\_\ |_|_| |_|  \__|_| |_|\___| |_|   \__,_|_|  |_|\_\  #
#                                                                               #
#===============================================================================#

#===============================================================================#
#                                                                               #
#                           (c) Efnilite 2020-2022                              #
#                                                                               #
#===============================================================================#

# -= Auto updater =-
# The auto updater will automatically download updates if they are available.
# It's highly recommended to keep this on!
auto-updater: true

# -= Enable joining =-
# Whether players can join the parkour.
# True = players can join, false = players can't join.
enable-joining: true

# -= Join-leave messages =-
# Whether players should receive a message when a player joins the parkour.
# True = players will receive a message when a new player joins, false = players won't get a message.
join-leave-messages: true

# -= BungeeCord options =-
# Change the BungeeCord settings.
# This also applies to servers who only want to run this plugin.
bungeecord:

  # -= BungeeCord enabled =-
  # Enabling this will make players who join the server automatically join the parkour.
  # You can enable this even without BungeeCord to make this a parkour-only server.
  # True = players will automatically join the parkour on join, false = players have to use the menu/parkour command.
  enabled: false

  # -= BungeeCord return server =-
  # The server the players will be returned to after they leave.
  return_server: 'Lobby'

  # -= Go back enabled =-
  # Whether players should be teleported to a specific location after leaving.
  # True = players get teleported to a specific location when they leave, false = they go to their location when they joined.
  go-back-enabled: false

  # -= Go back location =-
  # The place players will go back to when they leave
  # Only applies if BungeeCord mode is disabled and the go-back-enabled option is true.
  # Syntax: '(x,y,z,worldName)'
  go-back: '(0,100,0,world)'

# -= MySQL =-
# The options for using MySQL as storage.
sql:

  # -= MySQL enabled =-
  # Using databases makes you able to sync player data across multiple servers.
  # True = data will be stored in a database, false = data will be stored locally.
  enabled: false

  # -= MySQL settings =-
  url: 'localhost'
  port: 3306
  username: 'efnilite'
  password: 'super secret password'
  database: 'witp'

  # -= MySQL prefix =-
  # The prefix given to any table names
  # The default is ''. Example: 'witp-' -> this would make the table 'witp-players'
  prefix: ''

# -= World options =-
world:

  # -= World name =-
  # The world in which parkour will take place
  name: 'witp'

  # -= Delete world on reload =-
  # Deletes the world on reload/restart of the server.
  # This makes sure there are no ghost blocks left when a server crash occurs.
  # Disable this if you want to have a custom map.
  delete-on-reload: true

  # -= World fall back =-
  # The world players will be teleported to if they accidentally join the Parkour world without joining
  fall-back: 'world'

options:

  # If the options menu is enabled
  enabled: true

  # Options for the leads
  leads:

    # The amounts of the lead
    # This must be a whole number, and you can't have more than 9 options (the first 9 will be selected).
    # Also must be above 1
    amount:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 10

  # Options for the time option
  time:

    # Selects the time format.
    # Choose between:
    # 24 - 24 hour clock. (00:00, 12:00, 23:59)
    # 12 - 12 hour clock. (12:00 AM, 12:00 PM, 11:59 PM)
    format: 24

  # Enables/disables the inventory handling system
  inventory-handling: true

  # Logs inventories of the players that join to the inventories/ folder.
  # It is highly recommended to keep this enabled. Server crashes or errors while leaving might cause
  # inventories of players to be lost if this is set to false!
  # This only saves essential data like names, lore, enchantments and damage. All other data may be lost!
  inventory-saving: true

  # Alternate inventory saving command
  # Example: /inventory save %player%
  # This command will be executed by console.
  alt-inventory-saving-command: ''

  # Enables/disables the health handling system
  # Disable this if you're experiencing errors with max health, etc.
  health-handling: true

  # Saves things like health and max health for when a player joins the parkour.
  save-stats: true

  # If enabled, puts the hotbar quit item in slot 8 of players' inventories.
  hotbar-quit-item: false

# Options for permissions.
# These permissions are used to determine which things the player can change.
# Find them at at https://efnilite.github.io/efnilite.dev/wiki/witp
permissions:

  # If permission handling is enabled
  enabled: false

  # Per style permission
  # Gives every style a permission. The permission is the name of the style.
  # Syntax: witp.option.styles.<style> - example: witp.option.styles.red
  # Useful for servers with ranks.
  per-style: false

# -= Focus mode options =-
focus-mode:

  # -= Focus mode enabled =-
  # If focus mode is enabled players can't use commands while in parkour.
  # Note: this might not work on all commands because Minecraft.
  enabled: false

  # -=
  # A whitelist for commands which ARE allowed during focus mode (if focus mode is enabled).
  # If you want to disable the default whitelisted commands you can remove every item in the list below.
  whitelist:
    - 'witp'
    - 'parkour'
    - 'msg'
    - 'r'
    - 'w'
    - 'whisper'
    - 'reply'
    - 'message'

# -= Styles options =-
styles:

  # -= Styles default =-
  # The default style
  default: 'red'

  # -= Styles list =-
  # The list of all available styles, which you can add to if you want.
  # For changes, you have to restart or reload your server.
  list:
    red: [red_wool, red_stained_glass, red_concrete, red_terracotta]
    blue: [blue_wool, blue_stained_glass, blue_concrete, blue_terracotta]
    light blue: [light_blue_wool, light_blue_stained_glass, light_blue_concrete, light_blue_terracotta]
    green: [green_wool, green_stained_glass, green_concrete, green_terracotta]
    lime: [lime_wool, lime_stained_glass, lime_concrete, lime_terracotta]
    cyan: [cyan_wool, cyan_stained_glass, cyan_concrete, cyan_terracotta]
    purple: [purple_wool, purple_stained_glass, purple_concrete, purple_terracotta]
    yellow: [yellow_wool, yellow_stained_glass, yellow_concrete, yellow_terracotta]
    gray: [gray_wool, gray_stained_glass, gray_concrete, gray_terracotta]
    end: [end_stone, end_stone_bricks, purpur_block, purpur_pillar]
    nether: [netherrack, nether_bricks, red_nether_bricks, chiseled_nether_bricks, nether_wart_block, nether_gold_ore, netherite_block, basalt]
    quartz: [smooth_quartz, chiseled_quartz_block, quartz_block, quartz_bricks, quartz_pillar]
    ocean: [prismarine, prismarine_bricks, dark_prismarine, sea_lantern]
    redstone: [observer, dispenser, redstone_block, piston, sticky_piston, redstone_lamp, target]
    overworld: [grass_block, stone, cobblestone, oak_log]
    ores: [diamond_ore, gold_ore, iron_ore, coal_ore, nether_gold_ore, lapis_ore, redstone_ore, emerald_ore, nether_quartz_ore]
    wood: [oak_planks, spruce_planks, jungle_planks, acacia_planks, birch_planks, dark_oak_planks, oak_log, spruce_log, jungle_log, birch_log, acacia_log, dark_oak_log]
    rainbow: [red_wool, blue_wool, orange_wool, magenta_wool, lime_wool, purple_wool, yellow_concrete, orange_concrete, lime_concrete, light_blue_concrete, yellow_stained_glass, white_stained_glass, magenta_stained_glass, light_blue_stained_glass]
    glow: [glowstone, jack_o_lantern, beacon, sea_lantern, crying_obsidian, shroomlight]

# -= Scoring options =-
scoring:

  # -= All points =-
  # This will give the player all possible points.
  # If a player skips a block jump, it will still give the points for that block.
  all-points: false

  # -= Rewards use total score =-
  # Whether interval rewards should use the total score of a session or not.
  # The total score doesn't reset when a player falls.
  rewards-use-total-score: false

# -= Particle options =-
particles:

  # -= Particle shape =-
  # The shape of the particle that will appear when a new block generates.
  # Possible options: dot, box, circle
  particle-shape: 'box'

  # -= Particle type =-
  # The type of particle that will appear when a new block generates.
  # You can find all types at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  particle-type: 'SPELL_INSTANT'

  # -= Sound type =-
  # The sound that will play when a new block generates.
  # You can find all sounds at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sound-type: 'BLOCK_NOTE_BLOCK_GUITAR'

  # -= Sound pitch =-
  # The pitch of the sound that will play when a new block generates.
  sound-pitch: 3