name: 'WITP'
description: 'Infinitely automatically generating parkour plugin.'
author: Efnilite, Ice_Pancake
version: ${project.version}
api-version: 1.16
main: dev.efnilite.ip.IP
softdepend: [floodgate, vilib, Vault, PlaceholderAPI, Multiverse-Core, HolographicDisplays, VoidGen]
commands:
    witp:
        aliases: [parkour, ip]
        usage: /<command> [arguments]
        description: Main command for Infinite Parkour