name: 'WITP'
description: 'Infinitely automatically generating parkour plugin.'
author: Efnilite, Ice_Pancake
version: 3.5.1
api-version: 1.16
main: dev.efnilite.ip.IP
depend: [vilib]
softdepend: [Vault, PlaceholderAPI, ProtocolAPI, Multiverse-Core, HolographicDisplays, NoteBlockAPI, VoidGen]
commands:
    witp:
        aliases: [parkour, ip]
        usage: /<command> [arguments]
        description: Main command for Infinite Parkour