#===============================================================================$
#   __          __   _ _      _         _   _            _____           _      #
#   \ \        / /  | | |    (_)       | | | |          |  __ \         | |     #
#    \ \  /\  / /_ _| | | __  _ _ __   | |_| |__   ___  | |__) |_ _ _ __| | __  #
#     \ \/  \/ / _` | | |/ / | | '_ \  | __| '_ \ / _ \ |  ___/ _` | '__| |/ /  #
#      \  /\  / (_| | |   <  | | | | | | |_| | | |  __/ | |  | (_| | |  |   <   #
#       \/  \/ \__,_|_|_|\_\ |_|_| |_|  \__|_| |_|\___| |_|   \__,_|_|  |_|\_\  #
#                                                                               #
#===============================================================================#

#===============================================================================#
#                                                                               #
#                        (c) Efnilite 2020-2021                                 #
#                                                                               #
#===============================================================================#

# Enable metrics
# Metrics is for collecting anonymous server data (about the plugin)
metrics: true

# Verbosing
# If this is set to true it will display extra data when stuff happens (useful for developers)
verbose: false

# Options about Bungeecord/autojoining
bungeecord:

    # Enabling this will make players who join the server (that's running this plugin) automatically join the game on that server
    # !! If this is disabled, you have to use /witp join to join and /witp leave to leave. !!
    enabled: true

    # The server the players will be returned to after the game is done
    return_server: Lobby

    # If go back is enabled
    go-back-enabled: false

    # The place players will go back to if they leave, if bungeecord is disabled and the go-back option is enabled
    # You need to retain this format, or else it won't work: '(x,y,z,world)'
    go-back: '(0,150,0,world)'

# Options for MySQL
sql:
    enabled: false
    url: 'localhost'
    port: 3306
    database: 'witp'
    username: efnilite
    password: mynamejeff

# Options for the world
world:
    # The world in which the personal parkours will take place
    name: witp

    # The world players will be teleported to if they accidentally join the WITP world without being a player
    fall-back: world

# Options for lead
lead:
    # If the choosing of the lead can be changed
    enabled: true

    # The amounts of the lead
    # This must be a whole number, and you can't have more than 9 options (the first 9 will be selected).
    amount:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7

# Options for permissions
# These permissions are used to determine which things the player can change.
# List: https://github.com/Efnilite/Walk-in-the-Park/wiki/Permissions
permissions:

    # If permissions are enabled
    enabled: false

# Options for focus mode
focus-mode:

    # If focus mode is enabled players can't use commands while in parkour
    enabled: false

# Options for the option menu
options:

    # If options are enabled
    enabled: true

    # The item
    item: compass

    # Enables/disables the inventory handling system
    inventory-handling: true

# If changing time is enabled
time:
    enabled: true

# The different styles players can select
styles:

    # If styles are enabled
    enabled: true

    # The default style
    default: red

    # The list of all available styles, which you can add to if you want
    list:
        red: [red_wool, red_stained_glass, red_concrete, red_terracotta]
        blue: [blue_wool, blue_stained_glass, blue_concrete, blue_terracotta]
        light blue: [light_blue_wool, light_blue_stained_glass, light_blue_concrete, light_blue_terracotta]
        green: [green_wool, green_stained_glass, green_concrete, green_terracotta]
        lime: [lime_wool, lime_stained_glass, lime_concrete, lime_terracotta]
        cyan: [cyan_wool, cyan_stained_glass, cyan_concrete, cyan_terracotta]
        purple: [purple_wool, purple_stained_glass, purple_concrete, purple_terracotta]
        yellow: [yellow_wool, yellow_stained_glass, yellow_concrete, yellow_terracotta]
        gray: [gray_wool, gray_stained_glass, gray_concrete, gray_terracotta]
        end: [end_stone, end_stone_bricks, purpur_block, purpur_pillar]
        nether: [netherrack, nether_bricks, red_nether_bricks, chiseled_nether_bricks, nether_wart_block, nether_gold_ore, netherite_block, basalt]
        quartz: [smooth_quartz, chiseled_quartz_block, quartz_block, quartz_bricks, quartz_pillar]
        ocean: [prismarine, prismarine_bricks, dark_prismarine, sea_lantern]
        redstone: [observer, dispenser, redstone_block, piston, sticky_piston, redstone_lamp, target]
        overworld: [grass_block, stone, cobblestone, oak_log]
        ores: [diamond_ore, gold_ore, iron_ore, coal_ore, nether_gold_ore, lapis_ore, redstone_ore, emerald_ore, nether_quartz_ore]
        wood: [oak_planks, spruce_planks, jungle_planks, acacia_planks, birch_planks, dark_oak_planks, oak_log, spruce_log, jungle_log, birch_log, acacia_log, dark_oak_log]

# Options for custom rewards
rewards:

    # If rewards are enabled
    enabled: false

    # The interval at which they get a reward
    # (so for every 50 blocks the player jumps, they get a reward)
    # (this means doing a run of 27 and 23 will still get you coins even though you haven't had a score of 50)
    # Setting this to -1 will never result in rewards
    interval: 50

    # The same as interval, but instead at scores.
    # So when the player reaches, for example, 50 points, the rewards system is triggered.
    # Setting this to -1 will never result in rewards
    score: -1

    # The command that will be executed if the interval is met.
    # Use %player% to get the player
    # 'null' means no command
    command: 'null'

    # The amount of money players will receive as Vault currency
    vault-reward: 5

    # The message you get after the interval is met
    # 'null' means no message
    message: '&6+5 coins'

# Options for particles/sounds
particles:

    # The particle type
    # Use this list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html or else it won't work
    particle-type: 'SPELL_INSTANT'

    # The sound type
    # Use this list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html or else it won't work
    sound-type: 'BLOCK_NOTE_BLOCK_GUITAR'

    # The pitch of the sound
    sound-pitch: 3